### ISSUE TITLE
Cannot load catalogs

### ISSUE THREAD

**Issue by dspagnolo09** [parklab/MuSiCal#71]
Hello!

I followed the instructions for "Install from Source" in your README (I also checked to see if there was a recipe to install the package from conda using `conda search *musical*` and via the bioconda site, and didn't find anything, which is why I went with install from source). 

I am able to import MuSiCal in Python but when I run `musical.load_catalog()` I get the following error message
```
FileNotFoundError: [Errno 2] No such file or directory: /opt/miniconda3/envs/{MYENVNAME}/lib/python3.10/site-packages/musical/data/COSMIC-MuSiCal_v3p2_SBS_WGS.csv'
```
The same error persists both in Jupyter and invoking Python in the console, so shouldn't be a kernel issue. 

Inside the `.../site-packages/musica/data/` directory there was only a `__pycache__` directory and one py script, no further files. 

Can you please advise on how to fix this issue? Possibly there was a problem with my installation? Though I used pip inside my conda environment and there were no issues reported. All dependencies were previously installed via conda.

**Comment by dspagnolo09** [comment]
Was able to get this to work by copying files from `/Path/To/MuSiCal/musical/data/` to `/opt/miniconda3/envs/{MYENVNAME}/lib/python3.10/site-packages/musical/data/`

**Comment by Hu-JIN** [comment]
Hi,

Apologies for the issue and thanks for catching it! Previously there was no problem with `pip install -e`, but with `pip install`, the data files were not properly installed. This is now fixed with https://github.com/parklab/MuSiCal/commit/88e13c5e2e0d370a5c2c18079b4f23120cfd103b. 

If you uninstall, clone the package, and install again, it should work.
