### ISSUE TITLE
Cohort Stratification Error

### ISSUE THREAD

**Issue by jfajn** [parklab/MuSiCal#76]
I am trying to stratify my cohort and get an error during the following step:
k, clusters, Xs, model = musical.preprocessing.stratify_samples(X.values, H.values)

This is the error I receive: 
MuSiCal/MuSiCal-main/musical/cluster.py:181: RuntimeWarning: divide by zero encountered in log
  self.Wk_log = np.log(self.Wk)
MuSiCal/MuSiCal-main/musical/cluster.py:195: RuntimeWarning: divide by zero encountered in log
  self.Wk_log_ref_all = np.log(self.Wk_ref_all)
python37_musical/lib/python3.11/site-packages/numpy/core/_methods.py:173: RuntimeWarning: invalid value encountered in subtract x = asanyarray(arr - arrmean)
MuSiCal/MuSiCal-main/musical/cluster.py:206: RuntimeWarning: invalid value encountered in subtract
  self.gap_statistic_log = self.Wk_log_ref - self.Wk_log

Here is the beginning of my H.values:
array([[ 13.02370177,  22.36663251,   4.58321832,   2.30586172,
          6.80032626,   7.65084841,  20.57174326,  13.90007932,
         29.7988945 ,   0.87010952,  11.40108359,  37.65595118,
          3.78449284,   9.85849575,   8.67073113,   4.58633285],

And the beginning of X.values:
array([[8, 3, 3, ..., 0, 0, 1],

This is WXS data by the way. Thanks for your help!

**Comment by Hu-JIN** [comment]
Thanks for reporting this. The messages are warnings due to taking the log of 0, instead of errors. The results should be fine though, because we are not using the log version of the gap statistic, although the calculation of it is still attempted. So in short, you can ignore these warnings. 

The root cause of the warnings is the following. Looking at the H.values you provided, it seems that you have only 16 samples. If so, you can lower the `max_k` value when calling `stratify_samples`. For example, you can try `stratify_samples(X.values, H.values, max_k=5)`. The `max_k` value is the largest number of clusters the algorithm will consider. By default, it is 20. In this case, when attempting to cluster 16 samples into too many clusters, each sample will be put in its own cluster, resulting in the warning messages. 

I'll modify the code to handle this more gracefully in the future, either by dealing with the log of zeros directly, or by simply adjusting the default `max_k` according to the number of samples.

**Comment by jfajn** [comment]
Thank you so much!
